completed 1st SPARQL guide
aws/graph-notebook pull request #316
Opened 2022-07-06 14:41 UTC by charlesivie

Issue #, if available:

Description of changes:

The first of some SPARQL tutorials to be included in the notebooks. This is the basics. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-12 00:11 UTC, krlawrence requested changes
I need to finish reading but suggested a few upfront wording changes

2022-07-12 00:11 UTC, krlawrence commented on src/graph_notebook/notebooks/06-Language-Tutorials/01-SPARQL/01-SPARQL-BASICS.ipynb
> +    "In reality, Semantic Web knowledge graph databases are a very easy and intuitive way to understand, record and traverse data. In our opinion, much easier to use than relational databases. \n",
I suggest rewording this a little from "In our opinion...." to something like "This is often easier to do using graph databases, and graph query languages, as they are optimized for these types of operation"

2022-07-12 00:11 UTC, krlawrence commented on src/graph_notebook/notebooks/06-Language-Tutorials/01-SPARQL/01-SPARQL-BASICS.ipynb
> +    "This guide will show you how easy it is to use the powerful features of RDF and SPARQL, and as long as you have a general understanding of how to use a REST API, and some experience with some ot
This guide shows

2022-07-12 16:07 UTC, joywa commented on src/graph_notebook/notebooks/06-Language-Tutorials/01-SPARQL/01-SPARQL-BASICS.ipynb
> +     "image/png": "iVBORw0KGgoAAAANSUhEUgAACJ4AAANuCAYAAABdPFG6AAAMa2lDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnluSkJDQAqFICb0JIr1ICaFFEJAq2AhJIKHEmBBU7Kio4FpQEcWKrooouhZAFhWxl0Wx98WCysq6WFAUlTchAV32le+d75s7
Would be nice to have a graphic of this too

2022-07-12 16:09 UTC, joywa commented on src/graph_notebook/notebooks/06-Language-Tutorials/01-SPARQL/01-SPARQL-BASICS.ipynb
> +     "image/png": "iVBORw0KGgoAAAANSUhEUgAACJ4AAANuCAYAAABdPFG6AAAMa2lDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnluSkJDQAqFICb0JIr1ICaFFEJAq2AhJIKHEmBBU7Kio4FpQEcWKrooouhZAFhWxl0Wx98WCysq6WFAUlTchAV32le+d75s7
I think this data is a bit hard to relate to for a beginner who doesn't know about "TheSemanticWeb" and the related books.

2022-07-12 16:10 UTC, joywa commented on src/graph_notebook/notebooks/06-Language-Tutorials/01-SPARQL/01-SPARQL-BASICS.ipynb
> +     "image/png": "iVBORw0KGgoAAAANSUhEUgAACJ4AAANuCAYAAABdPFG6AAAMa2lDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnluSkJDQAqFICb0JIr1ICaFFEJAq2AhJIKHEmBBU7Kio4FpQEcWKrooouhZAFhWxl0Wx98WCysq6WFAUlTchAV32le+d75s7
OPTIONAL clause

2022-07-12 16:13 UTC, joywa commented on src/graph_notebook/notebooks/06-Language-Tutorials/01-SPARQL/01-SPARQL-BASICS.ipynb
> +     "image/png": "iVBORw0KGgoAAAANSUhEUgAACJ4AAANuCAYAAABdPFG6AAAMa2lDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnluSkJDQAqFICb0JIr1ICaFFEJAq2AhJIKHEmBBU7Kio4FpQEcWKrooouhZAFhWxl0Wx98WCysq6WFAUlTchAV32le+d75s7
Not sure why it shows 2. on here, but on the preview in your branch, it shows "1. Only return Authors who have published something..." Can you verify?

https://github.com/aws/graph-notebook/blob/SPARQL-TUTORIAL/src/graph_notebook/notebooks/06-Language-Tutorials/01-SPARQL/01-SPARQL-BASICS.ipynb

2022-07-12 16:14 UTC, joywa commented on src/graph_notebook/notebooks/06-Language-Tutorials/01-SPARQL/01-SPARQL-BASICS.ipynb
> +     "image/png": "iVBORw0KGgoAAAANSUhEUgAACJ4AAANuCAYAAABdPFG6AAAMa2lDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnluSkJDQAqFICb0JIr1ICaFFEJAq2AhJIKHEmBBU7Kio4FpQEcWKrooouhZAFhWxl0Wx98WCysq6WFAUlTchAV32le+d75s7
Nit: We haven't talked about periods in these SPARQL queries. Are they necessary? Why do some lines have them and others not? Is the spacing before a period important at all?

2022-07-12 16:40 UTC, joywa commented on src/graph_notebook/notebooks/06-Language-Tutorials/01-SPARQL/01-SPARQL-BASICS.ipynb
> +     "image/png": "iVBORw0KGgoAAAANSUhEUgAACJ4AAANuCAYAAABdPFG6AAAMa2lDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnluSkJDQAqFICb0JIr1ICaFFEJAq2AhJIKHEmBBU7Kio4FpQEcWKrooouhZAFhWxl0Wx98WCysq6WFAUlTchAV32le+d75s7
Using GROUP BY clause and filters

2022-07-12 16:41 UTC, joywa commented on src/graph_notebook/notebooks/06-Language-Tutorials/01-SPARQL/01-SPARQL-BASICS.ipynb
> +     "image/png": "iVBORw0KGgoAAAANSUhEUgAACJ4AAANuCAYAAABdPFG6AAAMa2lDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnluSkJDQAqFICb0JIr1ICaFFEJAq2AhJIKHEmBBU7Kio4FpQEcWKrooouhZAFhWxl0Wx98WCysq6WFAUlTchAV32le+d75s7
I think we should show this example first to demonstrate the benefit provided by GROUP BY. Also numbering is off again in the actual notebook.

2022-07-12 16:42 UTC, joywa commented on src/graph_notebook/notebooks/06-Language-Tutorials/01-SPARQL/01-SPARQL-BASICS.ipynb
> +     "image/png": "iVBORw0KGgoAAAANSUhEUgAACJ4AAANuCAYAAABdPFG6AAAMa2lDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnluSkJDQAqFICb0JIr1ICaFFEJAq2AhJIKHEmBBU7Kio4FpQEcWKrooouhZAFhWxl0Wx98WCysq6WFAUlTchAV32le+d75s7
Is it ok for this GROUP BY to not be capitalized?

2022-07-12 16:52 UTC, joywa commented on src/graph_notebook/notebooks/06-Language-Tutorials/01-SPARQL/01-SPARQL-BASICS.ipynb
> +     "image/png": "iVBORw0KGgoAAAANSUhEUgAACJ4AAANuCAYAAABdPFG6AAAMa2lDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnluSkJDQAqFICb0JIr1ICaFFEJAq2AhJIKHEmBBU7Kio4FpQEcWKrooouhZAFhWxl0Wx98WCysq6WFAUlTchAV32le+d75s7
Using LIMIT clause

2022-07-12 16:55 UTC, joywa commented on src/graph_notebook/notebooks/06-Language-Tutorials/01-SPARQL/01-SPARQL-BASICS.ipynb
> +     "image/png": "iVBORw0KGgoAAAANSUhEUgAACJ4AAANuCAYAAABdPFG6AAAMa2lDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnluSkJDQAqFICb0JIr1ICaFFEJAq2AhJIKHEmBBU7Kio4FpQEcWKrooouhZAFhWxl0Wx98WCysq6WFAUlTchAV32le+d75s7
Using the ORDER BY clause

2022-07-12 16:55 UTC, joywa commented on src/graph_notebook/notebooks/06-Language-Tutorials/01-SPARQL/01-SPARQL-BASICS.ipynb
> +     "image/png": "iVBORw0KGgoAAAANSUhEUgAACJ4AAANuCAYAAABdPFG6AAAMa2lDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnluSkJDQAqFICb0JIr1ICaFFEJAq2AhJIKHEmBBU7Kio4FpQEcWKrooouhZAFhWxl0Wx98WCysq6WFAUlTchAV32le+d75s7
"alphabetically"

2022-07-12 16:56 UTC, joywa commented on src/graph_notebook/notebooks/06-Language-Tutorials/01-SPARQL/01-SPARQL-BASICS.ipynb
> +     "image/png": "iVBORw0KGgoAAAANSUhEUgAACJ4AAANuCAYAAABdPFG6AAAMa2lDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnluSkJDQAqFICb0JIr1ICaFFEJAq2AhJIKHEmBBU7Kio4FpQEcWKrooouhZAFhWxl0Wx98WCysq6WFAUlTchAV32le+d75s7
Using DISTINCT clause

2022-07-12 16:57 UTC, joywa commented on src/graph_notebook/notebooks/06-Language-Tutorials/01-SPARQL/01-SPARQL-BASICS.ipynb
> +     "image/png": "iVBORw0KGgoAAAANSUhEUgAACJ4AAANuCAYAAABdPFG6AAAMa2lDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnluSkJDQAqFICb0JIr1ICaFFEJAq2AhJIKHEmBBU7Kio4FpQEcWKrooouhZAFhWxl0Wx98WCysq6WFAUlTchAV32le+d75s7
Using COUNT _____. Is this a clause, filter, function, or something else?

2022-07-12 16:58 UTC, joywa commented on src/graph_notebook/notebooks/06-Language-Tutorials/01-SPARQL/01-SPARQL-BASICS.ipynb
> +     "image/png": "iVBORw0KGgoAAAANSUhEUgAACJ4AAANuCAYAAABdPFG6AAAMa2lDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnluSkJDQAqFICb0JIr1ICaFFEJAq2AhJIKHEmBBU7Kio4FpQEcWKrooouhZAFhWxl0Wx98WCysq6WFAUlTchAV32le+d75s7
We should add a Conclusion section with calls-to-action. E.g., linking to additional notebooks, link to sample tutorials, link to console to create a new cluster and notebook today.. Check out the Sample Applications notebook conclusions for ideas.

2022-07-26 17:09 UTC, joywa commented
Worked with @charlesivie offline, latest draft looks good for merging.

2022-07-26 17:29 UTC, krlawrence submitted a review, later dismissed

2022-07-26 23:28 UTC, michaelnchin approved these changes

2022-07-26 23:59 UTC, merged