adding fraud detection with inductive inference notebook
aws/graph-notebook pull request #417
Opened 2022-12-22 03:03 UTC by sojiadeshina

Issue #, if available:

Description of changes:

Adding a notebook demonstrating real-time inductive inference on a fraud detection use case
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-01-24 01:48 UTC, bechbd submitted a review, later dismissed
Reviewed and commented offline.  All comments are now addressed

2023-02-02 17:10 UTC, joywa requested changes
Sent over a new copy with edits to @sojiadeshina offline. After addressing the 1 comment on the notebook, it is ready to go.

2023-02-02 22:27 UTC, sojiadeshina commented on src/graph_notebook/notebooks/04-Machine-Learning/Sample-Applications/03-Real-time-fraud-detection-with-Neptune-ML-inductive-inference.ipynb
> +   "cell_type": "code",
I added "First, let's install some required packages and make sure the neptune ml utility script is accessible"

2023-02-02 23:55 UTC, joywa approved these changes

2023-02-03 23:25 UTC, merged