Fixed issue where text on selection was not reverting back to black o…
aws/graph-notebook pull request #72
Opened 2021-02-26 01:10 UTC by bechbd

This fixes one half of issue 63 where the selected text was not changing back from white to blank after being unselected

2021-03-09 14:21 UTC, austinkline requested changes

2021-03-11 23:47 UTC, bechbd commented on src/graph_notebook/widgets/src/force_widget.ts
> +        node.font = { color: "black" };
This only applies to the items that do not have the group property set.  This only occurs when no grouping is possible so we are on the default/original color scheme.  Black was the text color in this case.

2021-03-17 23:14 UTC, austinkline commented on src/graph_notebook/widgets/src/force_widget.ts
> +        node.font = { color: "black" };
Got it, thanks for the clarification

2021-03-17 23:14 UTC, austinkline approved these changes

2021-03-22 18:03 UTC, merged